# Nocturne
background = #1B1B1B
foreground = #D8DEE9

# Standard colors
palette = 0=#1B1B1B
palette = 1=#D74E42
palette = 2=#A3BE8C
palette = 3=#EBCB8B
palette = 4=#5E81AC
palette = 5=#B48EAD
palette = 6=#8FBCBB
palette = 7=#D8DEE9

# Bright colors
palette = 8=#9A9D9A
palette = 9=#D74E42
palette = 10=#A3BE8C
palette = 11=#EBCB8B
palette = 12=#7AA2F0
palette = 13=#B48EAD
palette = 14=#8FBCBB
palette = 15=#E5E9F0
