# Nocturne
background = #1B1B1B
foreground = #D8DEE9

# Standard colors
palette = 0=#1B1B1B
palette = 1=#C56A60
palette = 2=#95AF7F
palette = 3=#D9BE7C
palette = 4=#5E81AC
palette = 5=#8A93A6
palette = 6=#7EA6A5
palette = 7=#D8DEE9

# Bright colors
palette = 8=#9A9D9A
palette = 9=#C56A60
palette = 10=#95AF7F
palette = 11=#D9BE7C
palette = 12=#7AA2F0
palette = 13=#94A0B5
palette = 14=#7EA6A5
palette = 15=#E5E9F0