$color = rgba(27, 27, 27, 1)
$inner_color = rgba(27, 27, 27, 0.7)
$outer_color = rgba(94, 129, 172, 1)
$font_color = rgba(216, 222, 233, 1)
$placeholder_color = rgba(216, 222, 233, 0.7)
$check_color = rgba(163, 190, 140, 1)
